# AOL/config/config.yaml

# --- PATHS ---
DATA_PATH: "data/anime_faces"
CHECKPOINT_PATH: "outputs/models"

# --- DATA PARAMETERS ---
IMAGE_SIZE: 64
CHANNELS: 3 # RGB
BUFFER_SIZE: 10000

# --- TRAINING PARAMETERS ---
EPOCHS: 100
BATCH_SIZE: 128
NOISE_DIM: 100
GEN_LR: 0.0001 # 1e-4
DISC_LR: 0.0001 # 1e-4
EPOCH_CHECKPOINT_SAVE_INTERVAL: 15